### ISSUE TITLE
Some confusions

### ISSUE THREAD

**Issue by huangjianhuster** [wrf/pdbcolor#1] opened 2019-11-15 03:07 UTC
Recently, I wanted to color a pdb structure in PyMol by my self-defined and extracted parameter about each amino acid. I felt so lucky to find this primal code which could finish this job perfectly.
However, I encountered some confusions while using the code.

After reading README.md file, I found out I could use pdb_color_generic.py to fulfill my purpose.
At the beginning, I tried the exact same example, the 3rze.pdb and 3rze.map.rates_features.csv, to help myself get familiar with this code.

I had done every step exactly as the instruction described. However, while I run the command line "pdb_color_generic.py -c 4 -d , -p 3rze.pdb -i 3rze.map.rates_features.csv -l blue -g dnds --exclude-first-group > 3rze.color_by_dnds.pml", an error popped out, which indicated 'TypeError: Nontype object is not iterable'. 
The wrong syntax was "For seqid in seqidlist".
The reason for this error seemd to be because seqidlist should be given by users. 

In the get_chains_only function, seqidlist parameter should be input by args.sequence, but args.sequence was not given in the command and its default value was None. And this would give the error when running "for seqid in seqidlist".

In the defined parser, parser.add_argument("-s","--sequence", nargs="*", help="sequence ID for PDB, give multiple names if data is available in the input file") points out this argument is necessary, while the previous command did not contain any "-s" information.

I was not sure I  run this code in the right way or maybe I missed something. 
The seqidlist seems that it should be consist of a list about proteinid so that "for seqid in seqidlist" and "if seqid.find('proteinid') > -1" in the code could work.

After this, I simply defined a function to help me find those proteinids in 3rze.pdb file and put them into a seqidlist. Then, the code could run through.
###-----------------------------------------------------------------------------------------------------------------------------###
Further analyzing the code, I was confused about the defined function read_generic_data:
(part code)
if type(chaincolumn) is int:
	chain = lsplits[int(chaincolumn)]
else:
	chain = "A"

chaincolumn seems should be str type since the 'else' syntax indicates default chain is 'A'.
However, the type of chaincolumn in the args.chain_column is always str and this function will always set the  varible "china" to 'A', no matter what chain_column you enter in the first place.
As for me, my input file has a chaincolumn which contains chain characters defined to indicate which chain each amino acid comes from, such as 'A', 'B', 'C' etc. Thus, this function set all my chains into 'A'.
This problem could be fixed by modifying the parse argument '--chain-column' with 'type = int' added in the parser.add_argument() sentence.
###-----------------------------------------------------------------------------------------------------------------------------###
In the make_output_script function:

#assign whole chain to lowest color, then build up
wayout.write("color {}{:02d}, chain {}\n".format( basecolor, int(value*binname_correction), chain ) )

this part seems could not achieve the purpose of setting the whole chain to the lowest color. The color parameter is 
 int(value*binname_correction) and the 'value' is generated by the following syntaxes:

for chain in keepchains.keys():
	chainoffset = refoffsets.get(chain, 0)
	scoregroups = defaultdict(list) # key is percent group, value is list of residues
	# for each residue, assign to a bin
		for residue in scoredict[chain].keys():
			esiduescore = scoredict[chain].get(residue,0.00)
			for i,value in enumerate(binvalues[:-1]):
				upper = binvalues[i+1]
				f residuescore < upper:
					scoregroups[value].append(residue - chainoffset)
					break

Assuming that keepchains.keys() contains four chain letters: 'A','B','C',and 'D'. For each iteration, let's say 'A' for example, each residue in socredict['A'].keys() will run the last 'for' iteration and genrate its own 'i' and 'value'. 
In this case, after every residue in chain 'A' is traversed, the 'i' and 'value' will be set according to the last residue of 
chain 'A'. And after all the chains is traversed,  the 'i' and 'value' will be set according to the last residue of 
chain 'D'. Still, I do not know how to fix this and considering targetcolors could be reversed, how should I find the lowest color for the whole chain is another problem the function should deal with.

###-----------------------------------------------------------------------------------------------------------------------------###
At last, I was confused about the function of 'refoffsets' variable. What does this varible do? To mark down the right sites of amino acid residues in PDB files? I could not say.
As for me, I simply delete 'chainoffset' in the following syntaxes:

[from make_output_script function]

for chain in keepchains.keys():
	chainoffset = refoffsets.get(chain, 0)
	scoregroups = defaultdict(list) # key is percent group, value is list of residues
	# for each residue, assign to a bin
		for residue in scoredict[chain].keys():
			esiduescore = scoredict[chain].get(residue,0.00)
			for i,value in enumerate(binvalues[:-1]):
				upper = binvalues[i+1]
				f residuescore < upper:
					#scoregroups[value].append(residue - chainoffset)
					scoregroups[value].append(residue)		
					break

and my PDB file in PyMol could select the right residues I wanted to color.

**Comment by wrf** [comment] 2019-11-15 09:07
You raise many points. I will try to address all of them. In general, it is difficult to make something easy to use that is also generic, since the user data can come in so many formats, and there is even some variability in the PDB format itself.

###

The command you gave that produces an error gives the correct output when run on my machine. Here are the args:
`base_color='blue', chain_column=None, data_column=4, default_chain='A', delimiter=',', exclude_first_group=True, exclude_middle_group=False, group_name='dnds', input_file='3rze.map.rates_features.csv', pdb='3rze.pdb', reverse_colors=False, sequence=None, site_column=0, zero_override=0.0`

The function get_chains_only() which has line 81 `for seqid in seqidlist`, exists only to extract the chain and sequence information directly from the PDB file, from the DBREF lines. This is to deal with PDB files that have multiple proteins. If no sequence is given to search for (something like ARNT_MOUSE, which is the SwissProt ID), then it assumes that you are going to be using the `default_chain`, which is A.

If you are getting that error, then you have a PDB file, with DBREF lines, but no sequence is given to search for, meaning that the user should be providing one. In the example, `3rze.pdb` from the same repo as the sample data does not have DBREF lines, while the one from rcsb.org does. The correct command should then be:

`pdb_color_generic.py -c 4 -d , -p 3rze.from_rcsb.pdb -i 3rze.map.rates_features.csv -l blue -g dnds --exclude-first-group -s HRH1_HUMAN`

###

For the chain column in read_generic_data(), this appears to be a bug. Thank you for bringing it to my attention, with the fix you suggest.

###

For the chain coloring, I'll admit that I have not tested with a good example with multiple chains. Looking over the code again, it still looks as though it should work as intended.

For each chain, iterate over the residues. Then, for each residue, iterate over the values of possible bins excluding the last bin. If the value of that residue is less than the value of the bin above it, keep that bin. Because the iteration is residue by residue, starting from the smallest bin, the effect is that all residues should be set to the lowest value unless the value is greater than another bin. There should not be any cross-over between chains.

For negative datasets, the reverse colors are suggested so that the most negative values would then appear brightly colored rather than gray.

There is not a way to control whether to reverse colors for individual chains. The script should just be run multiple times in that case. Sorry that I cannot help further.

###

Chain offset is to adjust residue numbers. Some PDB files have the residues numbered differently than the canonical protein. This generally should NOT happen, but occasionally does, often if the PDB was created with a trunctated protein or 6H tag or something. The offset is to correct the numbering, but that value should usually be 0, meaning no difference between the numbering in the structure and the canonical protein.

Thank you again for your interest. Please let me know if you have further problems.

**Comment by huangjianhuster** [comment] 2019-11-15 16:37
So happy to receive your reply and answers for my confusion.

Exactly, if a pdb file does not have the 'DBREF ' lines, the get_chains_only function works fine.
I downloaded the 3rze.pdb file from RCSB website since the original 3rze.pdb you used
while compiling this code was not present in the repo.
The current new version of 3rze.pdb contains:
DBREF  3RZE A   20   221  UNP    P35367   HRH1_HUMAN      20    221             
DBREF  3RZE A 1002  1161  UNP    P00720   LYS_BPT4         2    161             
DBREF  3RZE A  405   487  UNP    P35367   HRH1_HUMAN     405    487 
 Your explanation elucidates my confusion about this problem. Thanks a lot.

About the make_output_script function, your explanation was correct. My confusion contiues with the following sentences:

for chain in keepchains.keys(): # keys are chain letters, values are seq IDs
		chainoffset = refoffsets.get(chain, 0)
		scoregroups = defaultdict(list) # key is percent group, value is list of residues
		# for each residue, assign to a bin
		for residue in scoredict[chain].keys():
			residuescore = scoredict[chain].get(residue,0.00)
			for i,value in enumerate(binvalues[:-1]):
				upper = binvalues[i+1]
				if residuescore < upper:
					scoregroups[value].append(residue - chainoffset)
					break
			# should not need an else if last bin is large enough
		# assign whole chain to lowest color, then build up
		wayout.write("color {}{:02d}, chain {}\n".format( basecolor, int(value*binname_correction), chain ) )
		
	

I understand that the "for" iterations could put each residue of each chain into different color bins according to the value of the parameter (score).
My confusion is about the "wayout.write("color {}{:02d}, chain {}\n".format( basecolor, int(value*binname_correction), chain ) )".
After iteration of the residues in one chain, the enumerate function will set "i", "value" according to the last residue if the chain.

For example, let's say all scores in our sequences is positive (or zero) and range from 0 ~1. If the last residue of chain A is 10 and its residuescore = 0,
residuescore is clearly less than upper (upper = binvalues[1]) and then this last "for" iteration will break.
At this time, the wayout.write will write down the following message to pml file:
color blue00, chain A

However, if we change the residuescore of the last residue of chain A to 1, the for iteration will put this residue to the highest bin (excluding the last bin).
Then, the enumerate function will set "value" to the highest (near 1) .
At this time, the wayout.write will write down the following message to pml file:
color blue90, chain A

I upload my test.py file, test1.csv, test2.csv file for testing this part. You could check for details.
In the test.py file, all the functions are copied from your code without any modification. (except for find_seqid function ,which I defined to help me find proteinid)
Therefore, if this problem exists, maybe you need another method to set the whole chain to the lowest color.
#------------------------------------------------------------------------------------------------------------#
Here are my test.py output:
datadict1:
hide everything




[test.zip](https://github.com/wrf/pdbcolor/files/3852378/test.zip)


show cartoon
set_color colordefault, [0.75,0.75,0.58]
color colordefault, all
set_color blue00, [0.63,0.63,0.63]
set_color blue11, [0.5,0.58,0.68]
set_color blue22, [0.42,0.55,0.71]
set_color blue33, [0.35,0.52,0.73]
set_color blue45, [0.28,0.49,0.76]
set_color blue56, [0.2,0.46,0.8]
set_color blue67, [0.12,0.43,0.83]
set_color blue78, [0.0,0.38,0.87]
set_color blue90, [0.6,0,1]
color blue90, chain A
select 22_dnds_3_A, (chain A & resi 7)
color blue22, 22_dnds_3_A
select 45_dnds_5_A, (chain A & resi 8)
color blue45, 45_dnds_5_A
select 67_dnds_7_A, (chain A & resi 9)
color blue67, 67_dnds_7_A
select 90_dnds_9_A, (chain A & resi 10)
color blue90, 90_dnds_9_A
color blue90, chain B
select 11_dnds_2_B, (chain B & resi 2)
color blue11, 11_dnds_2_B
select 22_dnds_3_B, (chain B & resi 3)
color blue22, 22_dnds_3_B
select 33_dnds_4_B, (chain B & resi 4)
color blue33, 33_dnds_4_B
select 45_dnds_5_B, (chain B & resi 5)
color blue45, 45_dnds_5_B
select 56_dnds_6_B, (chain B & resi 6)
color blue56, 56_dnds_6_B
select 67_dnds_7_B, (chain B & resi 7)
color blue67, 67_dnds_7_B
select 78_dnds_8_B, (chain B & resi 8)
color blue78, 78_dnds_8_B
select 90_dnds_9_B, (chain B & resi 9)
color blue90, 90_dnds_9_B
#Reading scores from column 4 in 3rze.map.rates_features.csv, separated by ,
#Counted 508 lines with 268 scores
#Reading chain from PDB 3rze.pdb
###keeping chain A for sequence HRH1_HUMAN with offset 0
###keeping chain A for sequence HRH1_HUMAN with offset 0
###keeping chain A for sequence LYS_BPT4 with offset -1000
###keeping chain A for sequence HRH1_HUMAN with offset 0
##keeping chain A for sequence HRH1_HUMAN with offset 0
#Reading scores from column 3 in test.csv, separated by ,
#Counted 21 lines with 20 scores
#Generating list of bins from data
#data range from 0.00 to 0.90, diff of 0.90, median of 0.05
###lowest value is 0, best use sequential colors
#Generating PyMOL script for color scheme blue with bins of:
[0.0, 0.1125, 0.225, 0.3375, 0.45, 0.5625, 0.675, 0.7875, 0.9, 1.0]

-----------------------------------------------------------------------------------
datadict2:

hide everything
show cartoon
set_color colordefault, [0.75,0.75,0.58]
color colordefault, all
set_color blue00, [0.63,0.63,0.63]
set_color blue08, [0.5,0.58,0.68]
set_color blue17, [0.42,0.55,0.71]
set_color blue26, [0.35,0.52,0.73]
set_color blue35, [0.28,0.49,0.76]
set_color blue43, [0.2,0.46,0.8]
set_color blue52, [0.12,0.43,0.83]
set_color blue61, [0.0,0.38,0.87]
set_color blue70, [0.6,0,1]
color blue00, chain A
select 08_dnds_2_A, (chain A & resi 6)
color blue08, 08_dnds_2_A
select 26_dnds_4_A, (chain A & resi 7)
color blue26, 26_dnds_4_A
select 43_dnds_6_A, (chain A & resi 8)
color blue43, 43_dnds_6_A
select 70_dnds_9_A, (chain A & resi 9)
color blue70, 70_dnds_9_A
color blue00, chain B
select 08_dnds_2_B, (chain B & resi 1)
color blue08, 08_dnds_2_B
select 17_dnds_3_B, (chain B & resi 2)
color blue17, 17_dnds_3_B
select 26_dnds_4_B, (chain B & resi 3)
color blue26, 26_dnds_4_B
select 35_dnds_5_B, (chain B & resi 4)
color blue35, 35_dnds_5_B
select 43_dnds_6_B, (chain B & resi 5)
color blue43, 43_dnds_6_B
select 52_dnds_7_B, (chain B & resi 6)
color blue52, 52_dnds_7_B
select 70_dnds_9_B, (chain B & resi 7)
color blue70, 70_dnds_9_B
#Reading scores from column 3 in test2.csv, separated by ,
#Counted 21 lines with 20 scores
#Generating list of bins from data
#data range from 0.00 to 0.70, diff of 0.70, median of 0.00
###lowest value is 0, best use sequential colors
#Generating PyMOL script for color scheme blue with bins of:
[0.0, 0.0875, 0.175, 0.26249999999999996, 0.35, 0.4375, 0.5249999999999999, 0.6124999999999999, 0.7, 0.7999999999999999]

#------------------------------------------------------------------------------------------------------------#

At last, the Chain offset you explained seems to be useful when marking down the right sites in PDB files.
As for me, the chain offset of each chain in my input pdb file is not zero, but I still have to delete chainoffset in line "scoregroups[value].append(residue - chainoffset)"
in order to get the right sites colored. (still do not know why, may be because of the variability of pdb files, :))

Thank you again for your reply and explanation, helps a lot :)

**Comment by wrf** [comment] 2019-11-15 17:09
Ah yes, I see now. Value should be reset to the lowest value, so perhaps binvalues[0], rather than keeping the value from the for loop just above it.
Thank you again. I can try to fix this later.

**Comment by huangjianhuster** [comment] 2019-11-15 23:56
Glad to know that you realized that the lowest value of the whole chain which is set by wayout.write might be problematic.  Maybe I did not describe my confusion about this part clearly in my first comment :).
I think you have noticed that changing the lowest value by binvalues[0] is a solution for the circumstance where users do not reverse targetcolors.
Once I reverses the tragetcolors,  binvalues[0] is the highest/brightest color.
Thus, this was my confusion mentioned in my first comment previously.
And I do not know the best way to modify your code to fix this problem.
Thank you ! hope I could see your updated code soon!
This pdbcolor method is really useful, especially when we have to show parameters of residues of interest to others. A elegant way of visualization. really impressed!

**Comment by wrf** [comment] 2019-11-18 13:49
Using your test data, I believe it is now fixed. By default it uses the lowest, middle or highest bin, depending on the values present in the dataset. This can be changed with option `-O`. Thank you again for noticing this.

**Comment by huangjianhuster** [comment] 2019-11-19 10:41
Perfect! Happy to see your latest update :)

**Closed as completed** 2021-01-04 08:14 UTC
